### ISSUE TITLE
spring-cloud-azure-servicebus-topic-binder-sample post message failed with exception

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/spring-cloud-azure#237]
Sample [spring-cloud-azure-servicebus-topic-binder-sample](https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/spring-cloud-azure-servicebus-topic-binder-sample)

## Steps to Reproduce (for bugs)
* configure properties
* start application
* Run curl command:
`curl -X POST localhost:8080/messages?message=hello`
* server error log:
```
[http-nio-8080-exec-1] INFO com.microsoft.azure.spring.cloud.context.core.config.ResourceCreatingAspect - Calling getOrCreateServiceBusTopic with name 'xxxxx' ...
[http-nio-8080-exec-1] INFO com.microsoft.azure.spring.cloud.context.core.config.ResourceCreatingAspect - getOrCreateServiceBusTopic with name 'xxxxx' finished in 1.314 seconds
[http-nio-8080-exec-1] INFO com.microsoft.azure.servicebus.MessageSender - Creating MessagingFactory to namespace 'sb://xxxxx.servicebus.windows.net/'
[http-nio-8080-exec-1] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - Creating messaging factory from namespace endpoint uri 'sb://xxxx.servicebus.windows.net/'
[http-nio-8080-exec-1] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - Creating and starting reactor
[http-nio-8080-exec-1] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - Started reactor
[ReactorThread12446ae4-38fe-4037-8f05-bb08dc7ea779] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - starting reactor instance.
[ReactorThread12446ae4-38fe-4037-8f05-bb08dc7ea779] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - Creating connection to host 'xxxx.servicebus.windows.net:5671'
[ReactorThread12446ae4-38fe-4037-8f05-bb08dc7ea779] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - MessagingFactory opened.
[ReactorThread12446ae4-38fe-4037-8f05-bb08dc7ea779] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - Connection opened to host.
[ReactorThread12446ae4-38fe-4037-8f05-bb08dc7ea779] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - Creating CBS link to $cbs
[ForkJoinPool.commonPool-worker-5] INFO com.microsoft.azure.servicebus.MessageSender - Created MessagingFactory to namespace 'sb://xxxx.servicebus.windows.net/'
[ForkJoinPool.commonPool-worker-5] INFO com.microsoft.azure.servicebus.MessageSender - Creating MessageSender to entity 'xxxxx'
[ForkJoinPool.commonPool-worker-5] INFO com.microsoft.azure.servicebus.primitives.CoreMessageSender - Creating core message sender to 'xxxxx'
[pool-10-thread-1] WARN com.microsoft.azure.servicebus.primitives.CoreMessageReceiver - No messages received from 'xxx/subscriptions/xxxxx'. Pending receive request timed out. Returning null to the client.
[ForkJoinPool.commonPool-worker-0] INFO com.microsoft.azure.servicebus.primitives.RequestResponseLink - Opened requestresponselink to $cbs
[ForkJoinPool.commonPool-worker-0] INFO com.microsoft.azure.servicebus.primitives.MessagingFactory - Created CBS link to $cbs
[ReactorThread12446ae4-38fe-4037-8f05-bb08dc7ea779] INFO com.microsoft.azure.servicebus.primitives.CoreMessageSender - Creating send link to 'xxxxx'
[ReactorThread12446ae4-38fe-4037-8f05-bb08dc7ea779] INFO com.microsoft.azure.servicebus.primitives.CoreMessageSender - Opened send link to 'xxxxx'
[ForkJoinPool.commonPool-worker-0] INFO com.microsoft.azure.servicebus.MessageSender - Created MessageSender to entity 'xxxx'
[http-nio-8080-exec-1] INFO com.microsoft.azure.servicebus.TopicClient - Created topic client to connection string 'Endpoint=sb://xxxx.servicebus.windows.net/;EntityPath=xxxxx;'
[ForkJoinPool.commonPool-worker-0] ERROR com.microsoft.azure.servicebus.MessageAndSessionPump - Invocation of onMessage with message containing sequence number '1' threw unexpected exception
org.springframework.messaging.MessageHandlingException: Missing header 'azure_checkpointer' for method parameter type [interface com.microsoft.azure.spring.integration.core.api.Checkpointer], failedMessage=GenericMessage [payload=byte[5], headers={id=5876d43e-7165-865f-1a7e-cd6ee3bf3f90, contentType=application/json, timestamp=1536655295450}]
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.handleMissingValue(HeaderMethodArgumentResolver.java:105)
	at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:106)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:116)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:137)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:109)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:158)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:47)
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusTemplate$ServiceBusMessageHandler.onMessageAsync(ServiceBusTemplate.java:110)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$receiveAndPumpMessage$2(MessageAndSessionPump.java:137)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[ForkJoinPool.commonPool-worker-0] ERROR com.microsoft.azure.servicebus.MessageAndSessionPump - onMessage with message containing sequence number '1' threw exception
org.springframework.messaging.MessageHandlingException: Missing header 'azure_checkpointer' for method parameter type [interface com.microsoft.azure.spring.integration.core.api.Checkpointer], failedMessage=GenericMessage [payload=byte[5], headers={id=5876d43e-7165-865f-1a7e-cd6ee3bf3f90, contentType=application/json, timestamp=1536655295450}]
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.handleMissingValue(HeaderMethodArgumentResolver.java:105)
	at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:106)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:116)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:137)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:109)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:158)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:47)
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusTemplate$ServiceBusMessageHandler.onMessageAsync(ServiceBusTemplate.java:110)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$receiveAndPumpMessage$2(MessageAndSessionPump.java:137)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[ForkJoinPool.commonPool-worker-0] ERROR com.microsoft.azure.spring.integration.servicebus.ServiceBusTemplate - Exception encountered in phase USERCALLBACK
org.springframework.messaging.MessageHandlingException: Missing header 'azure_checkpointer' for method parameter type [interface com.microsoft.azure.spring.integration.core.api.Checkpointer], failedMessage=GenericMessage [payload=byte[5], headers={id=5876d43e-7165-865f-1a7e-cd6ee3bf3f90, contentType=application/json, timestamp=1536655295450}]
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.handleMissingValue(HeaderMethodArgumentResolver.java:105)
	at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:106)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:116)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:137)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:109)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:158)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:47)
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusTemplate$ServiceBusMessageHandler.onMessageAsync(ServiceBusTemplate.java:110)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$receiveAndPumpMessage$2(MessageAndSessionPump.java:137)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by warrenzhu25** [comment]
This issue cannot be reproduced. This might be caused by using older dependency. `mvn clean install` should fix the issue.

**Comment by amisai** [comment]
Hi,

I have the same problem. 

I've removed all _com.microsoft.azure_ dependencies from .m2 repository and run _mvn clean install_ just in case but the error still appears:

...
org.springframework.messaging.MessageHandlingException: Missing header 'azure_checkpointer' for method parameter type [interface com.microsoft.azure.spring.integration.core.api.Checkpointer], failedMessage=GenericMessage [payload=byte[6], headers={id=b2f49192-4630-9302-b9fd-33a1c3ea3ec4, contentType=application/json, timestamp=1537197899744}]
...
[ForkJoinPool.commonPool-worker-0] ERROR com.microsoft.azure.spring.integration.servicebus.ServiceBusTemplate - Exception encountered in phase USERCALLBACK
...

The error is related to the _@Header(AzureHeaders.CHECKPOINTER) Checkpointer checkpointer_ here: https://github.com/Microsoft/spring-cloud-azure/blob/master/spring-cloud-azure-samples/spring-cloud-azure-servicebus-topic-binder-sample/src/main/java/com/example/SinkExample.java#L27. If you mark the Header as optional (with required=false, f.i.) the error won't appear (but the message is not checkpointed and it keeps appearing each minute).

Also, I was able to consume the message using the TopicReceiveController class from another sample: https://github.com/Microsoft/spring-cloud-azure/blob/master/spring-cloud-azure-samples/spring-cloud-azure-servicebus-integration-sample/.

**Comment by warrenzhu25** [comment]
Property should be `spring.cloud.stream.servicebus.bindings.input.consumer.checkpoint-mode=MANUAL`. Will fix it.

**Comment by warrenzhu25** [comment]
Fixed.

**Comment by djangofan** [comment]
I was getting this issue because I copy pasted from a Consumer and defined a publisher Source interface method taking an argument of `@Header(AzureHeaders.CHECKPOINTER) Checkpointer checkpointer`  .   I just removed the checkpointer argument and now it works.  Not totally sure why this was the case.   I suspect checkpointing only makes sense on a consumer?

**Comment by saragluna** [comment]
@djangofan yes, the checkpointing only makes sense on a consumer.
